# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mode_C.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModeCWindow(object):
    def setupUi(self, ModeCWindow):
        ModeCWindow.setObjectName("ModeCWindow")
        ModeCWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/pic/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModeCWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ModeCWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(100, 80, 601, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 140, 561, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.original_image_path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.original_image_path.setFont(font)
        self.original_image_path.setText("")
        self.original_image_path.setClearButtonEnabled(True)
        self.original_image_path.setObjectName("original_image_path")
        self.gridLayout.addWidget(self.original_image_path, 1, 1, 1, 1)
        self.original_image_path_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.original_image_path_label.setFont(font)
        self.original_image_path_label.setAlignment(QtCore.Qt.AlignCenter)
        self.original_image_path_label.setObjectName("original_image_path_label")
        self.gridLayout.addWidget(self.original_image_path_label, 1, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.browse_button.setFont(font)
        self.browse_button.setAutoDefault(False)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 410, 561, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.next_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.next_button.setFont(font)
        self.next_button.setAutoDefault(False)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.exit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        ModeCWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModeCWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ModeCWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModeCWindow)
        self.statusbar.setObjectName("statusbar")
        ModeCWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ModeCWindow)
        self.next_button.clicked.connect(ModeCWindow.next_button_click)
        self.exit_button.clicked.connect(ModeCWindow.quit_button_click)
        self.browse_button.clicked.connect(ModeCWindow.browse_button_click)
        QtCore.QMetaObject.connectSlotsByName(ModeCWindow)

    def retranslateUi(self, ModeCWindow):
        _translate = QtCore.QCoreApplication.translate
        ModeCWindow.setWindowTitle(_translate("ModeCWindow", "Mode C - Class-specific Composition"))
        self.title_label.setText(_translate("ModeCWindow", "Mode C - Class-specific Composition"))
        self.original_image_path_label.setText(_translate("ModeCWindow", "Original Image\n"
"Path"))
        self.browse_button.setText(_translate("ModeCWindow", "Browse Origianl Image Path"))
        self.next_button.setText(_translate("ModeCWindow", "Next"))
        self.exit_button.setText(_translate("ModeCWindow", "Exit"))
import logo_icon_rc
