# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mode_A.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModeAWindow(object):
    def setupUi(self, ModeAWindow):
        ModeAWindow.setObjectName("ModeAWindow")
        ModeAWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/pic/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModeAWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ModeAWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(100, 80, 601, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 140, 561, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.patch_pixel_dir_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.patch_pixel_dir_2.setFont(font)
        self.patch_pixel_dir_2.setText("")
        self.patch_pixel_dir_2.setClearButtonEnabled(True)
        self.patch_pixel_dir_2.setObjectName("patch_pixel_dir_2")
        self.gridLayout.addWidget(self.patch_pixel_dir_2, 4, 1, 1, 1)
        self.mode = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mode.setFont(font)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.gridLayout.addWidget(self.mode, 1, 1, 1, 1)
        self.target_image_path_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.target_image_path_label.setFont(font)
        self.target_image_path_label.setAlignment(QtCore.Qt.AlignCenter)
        self.target_image_path_label.setObjectName("target_image_path_label")
        self.gridLayout.addWidget(self.target_image_path_label, 2, 0, 1, 1)
        self.target_image_path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.target_image_path.setFont(font)
        self.target_image_path.setText("")
        self.target_image_path.setClearButtonEnabled(True)
        self.target_image_path.setObjectName("target_image_path")
        self.gridLayout.addWidget(self.target_image_path, 2, 1, 1, 1)
        self.patch_pixel_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patch_pixel_label.setFont(font)
        self.patch_pixel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patch_pixel_label.setObjectName("patch_pixel_label")
        self.gridLayout.addWidget(self.patch_pixel_label, 4, 0, 1, 1)
        self.mode_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mode_label.setFont(font)
        self.mode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_label.setObjectName("mode_label")
        self.gridLayout.addWidget(self.mode_label, 1, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.browse_button.setFont(font)
        self.browse_button.setAutoDefault(False)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 3, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 410, 561, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.next_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.next_button.setFont(font)
        self.next_button.setAutoDefault(False)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.exit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        ModeAWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModeAWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ModeAWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModeAWindow)
        self.statusbar.setObjectName("statusbar")
        ModeAWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ModeAWindow)
        self.next_button.clicked.connect(ModeAWindow.next_button_click)
        self.exit_button.clicked.connect(ModeAWindow.quit_button_click)
        self.browse_button.clicked.connect(ModeAWindow.browse_button_click)
        QtCore.QMetaObject.connectSlotsByName(ModeAWindow)

    def retranslateUi(self, ModeAWindow):
        _translate = QtCore.QCoreApplication.translate
        ModeAWindow.setWindowTitle(_translate("ModeAWindow", "Mode A - Composite Image Generation"))
        self.title_label.setText(_translate("ModeAWindow", "Mode A - Composite Image Generation"))
        self.mode.setCurrentText(_translate("ModeAWindow", "Natural Image Set"))
        self.mode.setItemText(0, _translate("ModeAWindow", "Natural Image Set"))
        self.mode.setItemText(1, _translate("ModeAWindow", "Man-made Image Set"))
        self.mode.setItemText(2, _translate("ModeAWindow", "Both Image Sets"))
        self.target_image_path_label.setText(_translate("ModeAWindow", "Target Image\n"
"Path"))
        self.patch_pixel_label.setText(_translate("ModeAWindow", "Patch Pixel"))
        self.mode_label.setText(_translate("ModeAWindow", "Original Image"))
        self.browse_button.setText(_translate("ModeAWindow", "Browse Target Image"))
        self.next_button.setText(_translate("ModeAWindow", "Next"))
        self.exit_button.setText(_translate("ModeAWindow", "Exit"))
import logo_icon_rc
